### ISSUE TITLE
How to limitate the number of results displayed

### ISSUE THREAD

**Issue by sandoche** [nuxt-community/lunr-module#5]
Hi,

I get as many results as possible in the search results box,
Is there a way to only show the top 5?

I am currently doing it in CSS.

**Comment by pimlie** [comment]
There is no way to limit the search results themselves, but you should be able to provide a custom slot which renders nothing when `index > 4` . See the slot definition here for all scope props: https://github.com/nuxt-community/lunr-module/blob/master/lib/search.vue#L44

**Comment by sandoche** [comment]
I tried like this but didn't work very good for me because the li was still appearing.
But the css hack works pretty good :)
