### ISSUE TITLE
How to configure the search to have already some results if no full word has typed. 

### ISSUE THREAD

**Issue by PetrusHahol** [nuxt-community/lunr-module#7]
Hi!
Having issue to find some solution for nuxt with a search which will provide some answers without necessity to complete at least a word that matches with document body. 
Is here a way to configure the lunr such way? So far I need to put at least a word to have some result.

**Comment by pimlie** [comment]
Hey,

I believe most search implementations requires the user to indicate they want to do a wildcard/partial search. Here is how to do that with Lunr: https://lunrjs.com/guides/searching.html (ie just append a `*`)

**Comment by PetrusHahol** [comment]
Thank you, seems what I need. 
Is here some simple way how to adjust the search that will work like it has * in the end of each word? 😃

**Comment by PetrusHahol** [comment]
Made a WA of it on webhook side in nuxt.config.js. Just simply indexed some subparts of words in text

**Comment by sandoche** [comment]
@PetrusHahol I created a PR about this:
https://github.com/nuxt-community/lunr-module/pull/17

**Comment by PetrusHahol** [comment]
@sandoche Thank you for your contribution. I have badly looking WA for it, so now I will just remove it and make the solution of mine simpler :)

**Comment by sandoche** [comment]
You're welcome you can use this for now, until the PR is approved
```sh
npm install https://github.com/sandoche/lunr-module.git --save
```
